#pragma once

#include <smolrtsp/types/error.h>
#include <smolrtsp/types/header_map.h>
#include <smolrtsp/types/header.h>
#include <smolrtsp/types/message_body.h>
#include <smolrtsp/types/method.h>
#include <smolrtsp/types/reason_phrase.h>
#include <smolrtsp/types/request_line.h>
#include <smolrtsp/types/request_uri.h>
#include <smolrtsp/types/request.h>
#include <smolrtsp/types/response_line.h>
#include <smolrtsp/types/response.h>
#include <smolrtsp/types/rtsp_version.h>
#include <smolrtsp/types/status_code.h>
#include <smolrtsp/types/sdp.h>
#include <smolrtsp/types/rtp.h>
#include <smolrtsp/nal/h264.h>
#include <smolrtsp/nal/h265.h>
#include <smolrtsp/nal.h>
#include <smolrtsp/writer.h>
#include <smolrtsp/util.h>
#include <smolrtsp/transport.h>
#include <smolrtsp/rtp_transport.h>
#include <smolrtsp/nal_transport.h>
#include <smolrtsp/droppable.h>
#include <smolrtsp/controller.h>
#include <smolrtsp/io_vec.h>
#include <smolrtsp/context.h>
#include <smolrtsp/option.h>

#include <types/error.c>
#include <types/header_map.c>
#include <types/header.c>
#include <types/message_body.c>
#include <types/method.c>
#include <types/parsing.c>
#include <types/parsing.h>
#include <types/reason_phrase.c>
#include <types/request_line.c>
#include <types/request_uri.c>
#include <types/request.c>
#include <types/response_line.c>
#include <types/response.c>
#include <types/rtsp_version.c>
#include <types/status_code.c>
#include <types/sdp.c>
#include <types/rtp.c>
#include <nal/h264.c>
#include <nal/h265.c>
#include <nal.c>
#include <writer.c>
#include <writer/fd.c>
#include <writer/file.c>
#include <writer/string.c>
#include <util.c>
#include <transport/tcp.c>
#include <transport/udp.c>
#include <rtp_transport.c>
#include <nal_transport.c>
#include <io_vec.c>
#include <controller.c>
#include <context.c>
#include <macros.h>