name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          sh build.sh divinus-musl
          sh build.sh divinus-muslhf
          sh build.sh divinus-glibc
