name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          list="arm-glibc arm-musl3 arm-musl4 arm9-musl3 arm9-musl4 arm9-uclibc armhf-glibc armhf-musl mips-musl"
          for lib in $list; do
            sh build.sh $lib
            zip $lib divinus*
          done

      - name: Upload
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: ./*.zip
